/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DataExtraction } from "./DataExtraction";
import { DataExtractionCountArgs } from "./DataExtractionCountArgs";
import { DataExtractionFindManyArgs } from "./DataExtractionFindManyArgs";
import { DataExtractionFindUniqueArgs } from "./DataExtractionFindUniqueArgs";
import { DeleteDataExtractionArgs } from "./DeleteDataExtractionArgs";
import { DataExtractionService } from "../dataExtraction.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => DataExtraction)
export class DataExtractionResolverBase {
  constructor(
    protected readonly service: DataExtractionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "DataExtraction",
    action: "read",
    possession: "any",
  })
  async _dataExtractionsMeta(
    @graphql.Args() args: DataExtractionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [DataExtraction])
  @nestAccessControl.UseRoles({
    resource: "DataExtraction",
    action: "read",
    possession: "any",
  })
  async dataExtractions(
    @graphql.Args() args: DataExtractionFindManyArgs
  ): Promise<DataExtraction[]> {
    return this.service.dataExtractions(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => DataExtraction, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "DataExtraction",
    action: "read",
    possession: "own",
  })
  async dataExtraction(
    @graphql.Args() args: DataExtractionFindUniqueArgs
  ): Promise<DataExtraction | null> {
    const result = await this.service.dataExtraction(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => DataExtraction)
  @nestAccessControl.UseRoles({
    resource: "DataExtraction",
    action: "delete",
    possession: "any",
  })
  async deleteDataExtraction(
    @graphql.Args() args: DeleteDataExtractionArgs
  ): Promise<DataExtraction | null> {
    try {
      return await this.service.deleteDataExtraction(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
